apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/prometheus-stack
    repoURL: https://github.com/san40pan40/argocd-infra.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true