apiVersion: v2
name: infra-ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
