ingress-nginx:
  controller:
    service:
      type: NodePort
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      targetMemoryUtilizationPercentage: 80
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi