apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-1
  namespace: default
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/app-1
    repoURL: https://github.com/san40pan40/argocd-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true