apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  destination:
    namespace: nginx2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/nginx2
    repoURL: https://github.com/san40pan40/argocd-infra.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true